// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_2AaPxOCsc4gW1Fn3_GhajSytNwfbJQ',
    appId: '1:476596898735:web:042ec60a8ceb74c0263d5a',
    messagingSenderId: '476596898735',
    projectId: 'orphan-1dfe0',
    authDomain: 'orphan-1dfe0.firebaseapp.com',
    storageBucket: 'orphan-1dfe0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjovz6DfbyQR_v64VD_R0sr9s7SPOcfI',
    appId: '1:476596898735:android:e1cce29164f3e651263d5a',
    messagingSenderId: '476596898735',
    projectId: 'orphan-1dfe0',
    storageBucket: 'orphan-1dfe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcFX_eZ2dEQ-Tot8Qt7uqanz_69iUsXaw',
    appId: '1:476596898735:ios:39665d2db4e021dc263d5a',
    messagingSenderId: '476596898735',
    projectId: 'orphan-1dfe0',
    storageBucket: 'orphan-1dfe0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcFX_eZ2dEQ-Tot8Qt7uqanz_69iUsXaw',
    appId: '1:476596898735:ios:39665d2db4e021dc263d5a',
    messagingSenderId: '476596898735',
    projectId: 'orphan-1dfe0',
    storageBucket: 'orphan-1dfe0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_2AaPxOCsc4gW1Fn3_GhajSytNwfbJQ',
    appId: '1:476596898735:web:6e33cfb6efac0774263d5a',
    messagingSenderId: '476596898735',
    projectId: 'orphan-1dfe0',
    authDomain: 'orphan-1dfe0.firebaseapp.com',
    storageBucket: 'orphan-1dfe0.firebasestorage.app',
  );
}
