// lib/main.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <-- generated by flutterfire configure

// AUTH PAGES
import 'auth/login_page.dart';
import 'auth/signup_page.dart';
import 'auth/forget_password_page.dart';

// DASHBOARDS
import 'dashboards/admin_dashboard.dart' as admin_dash;
import 'dashboards/staff_dashboard.dart' as staff_dash;
import 'dashboards/donor_dashboard.dart' as donor_dash;

// FEATURE PAGES
import 'donation/donation_page.dart';

// PROVIDERS
import 'providers/donor_provider.dart';
import 'models/adoption_model.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase for the current platform
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => DonorProvider()),
        ChangeNotifierProvider(create: (_) => AdoptionModel()),
      ],
      child: const CareBridgeApp(),
    ),
  );
}

class CareBridgeApp extends StatefulWidget {
  const CareBridgeApp({super.key});

  @override
  State<CareBridgeApp> createState() => _CareBridgeAppState();
}

class _CareBridgeAppState extends State<CareBridgeApp> {
  bool isDarkMode = false;

  void toggleDarkMode(bool enabled) {
    setState(() {
      isDarkMode = enabled;
    });
  }

  @override
  Widget build(BuildContext context) {
    const primaryColor = Color(0xFF6347EB);

    return MaterialApp(
      title: "CareBridge",
      debugShowCheckedModeBanner: false,

      // LIGHT THEME
      theme: ThemeData(
        useMaterial3: true,
        primaryColor: primaryColor,
        scaffoldBackgroundColor: const Color(0xFFF6F8FB),
        fontFamily: "Roboto",
        colorScheme: ColorScheme.fromSeed(seedColor: primaryColor),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryColor,
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
      ),

      // DARK THEME
      darkTheme: ThemeData.dark().copyWith(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: primaryColor,
          brightness: Brightness.dark,
        ),
      ),

      themeMode: isDarkMode ? ThemeMode.dark : ThemeMode.light,

      home: AuthFlow(
        isDarkMode: isDarkMode,
        onThemeChanged: toggleDarkMode,
      ),
    );
  }
}

/// ===============================
/// AUTH FLOW CONTROLLER
/// ===============================
class AuthFlow extends StatefulWidget {
  final bool isDarkMode;
  final Function(bool) onThemeChanged;

  const AuthFlow({
    super.key,
    required this.isDarkMode,
    required this.onThemeChanged,
  });

  @override
  State<AuthFlow> createState() => _AuthFlowState();
}

class _AuthFlowState extends State<AuthFlow> {
  String currentView = "login";

  void changeView(String view) {
    setState(() {
      currentView = view;
    });
  }

  /// Determine user role
  String determineRole(String email, String password) {
    final cleanEmail = email.toLowerCase().trim();

    if (cleanEmail == "admin@carebridge.org" && password == "admin@") {
      return "admin";
    }

    if (cleanEmail == "staff@carebridge.org" && password == "staff@") {
      return "staff";
    }

    return "donor";
  }

  @override
  Widget build(BuildContext context) {
    switch (currentView) {
      case "login":
        return LoginPage(
          onSignedIn: (email, password) {
            final role = determineRole(email, password);
            changeView(role);
          },
          onGoToSignup: () => changeView("signup"),
          onGoToForgotPassword: () => changeView("forgot"),
        );

      case "signup":
        return SignupPage(
          onSignedUp: (email, password) => changeView("donor"),
          onGoToLogin: () => changeView("login"),
        );

      case "forgot":
        return ForgotPasswordPage(
          onResetEmailSent: () => changeView("login"),
          onGoToLogin: () => changeView("login"),
        );

      case "admin":
        return const admin_dash.AdminDashboard();

      case "staff":
        return const staff_dash.StaffDashboardPage();

      case "donor":
        return donor_dash.DonorDashboardPage(
          isDarkMode: widget.isDarkMode,
          onThemeChanged: widget.onThemeChanged,
        );

      default:
        return const Scaffold(
          body: Center(child: Text("Unknown View")),
        );
    }
  }
}